config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :profils
  resources :posts
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  get 'welcome/index'

   root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
    user ||= User.new # guest user
    
    if user.role? :super_admin
      can :manage, :all

      elsif user.role?(:author)
        can :create, Post
        can :update, Post do |post|
          post.try(:user) == user
        end
      end
    end
  end

app/models/post.rb
class Post < ActiveRecord::Base
belongs_to :user
mount_uploader :image, ImageUploader

end

app/models/profil.rb
class Profil < ActiveRecord::Base
belongs_to :user
mount_uploader :image, ImageUploader

end

app/models/role.rb
class Role < ActiveRecord::Base
has_and_belongs_to_many :users
end

app/models/story_model.rb
class StoryModel < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :confirmable,:recoverable, :rememberable, :trackable, :validatable

has_one :profil
has_many :posts
has_and_belongs_to_many :roles
def role?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_action :authenticate_user!


 rescue_from CanCan::AccessDenied do | exception | 
    flash[:error] = exception.message 
    redirect_to root_url
  end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource 
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    unauthorized! if cannot? :ubdate, @post
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :location, :date, :text, :photos, :privacy, :bus, :car, :boat, :plane, :walking, :train, :image)
    end
end

app/controllers/profils_controller.rb
class ProfilsController < ApplicationController
  before_action :set_profil, only: [:show, :edit, :update, :destroy]

  # GET /profils
  # GET /profils.json
  def index
    @profils = Profil.all
  end

  # GET /profils/1
  # GET /profils/1.json
  def show
     @myposts = current_user.posts
  end

  # GET /profils/new
  
  def new
    @profil = Profil.new
  if current_user.profil.blank?
    # create profil for user
  else
    # raise error which doesn't make sense or redirect like
    redirect_to profil_url(current_user)
  end
end

  # GET /profils/1/edit
  def edit
  end

  # POST /profils
  # POST /profils.json
  def create
    @profil = Profil.new(profil_params)
    @profil.user_id = current_user.id
    respond_to do |format|
      if @profil.save
        format.html { redirect_to @profil, notice: 'Profil was successfully created.' }
        format.json { render :show, status: :created, location: @profil }
      else
        format.html { render :new }
        format.json { render json: @profil.errors, status: :unprocessable_entity }
      
      end
    end
  end

  # PATCH/PUT /profils/1
  # PATCH/PUT /profils/1.json
  def update
    respond_to do |format|
      if @profil.update(profil_params)
        format.html { redirect_to @profil, notice: 'Profil was successfully updated.' }
        format.json { render :show, status: :ok, location: @profil }
      else
        format.html { render :edit }
        format.json { render json: @profil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profils/1
  # DELETE /profils/1.json
  def destroy
    @profil.destroy
    respond_to do |format|
      format.html { redirect_to profils_url, notice: 'Profil was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profil
      @profil = Profil.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profil_params
      params.require(:profil).permit(:first_name, :last_name, :bio, :city_of_origin, :current_location, :asylum_status, :email, :facebook, :twitter, :linkedin, :instagram, :dob, :gender, :image)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController 
  #before_filter :check_permissions, :only => [ :new, :create, :cancel ] 
  skip_before_filter :require_no_authentication 

  def check_permissions
    authorize! :create, resource
  end 
end 

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
 def index
    @stories = StoryModel.all
  end
def show
	@story =StoryModel.find(params[:id])
end 
	def new
 	end
 	#snippet for brevity
 	  def create
 	   @story = StoryModel.new(story_params)
 
  @story.save
  redirect_to @story_models
end
 
private
  def story_params
    params.require(:story).permit(:title, :text, :name, :email, :date)
      end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profils_helper.rb
module ProfilsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/posts/_form.html.erb
<div class="maincontant text-center">
<link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Baloo+Tamma" rel="stylesheet">

<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
  <i class="fa fa-bookmark-o" aria-hidden="true"></i>
    <%= f.label :title %><br>
    <%= f.text_field :title%>
  </div>
  <!-- <div class="field">
    <%= f.label :location %><br>
    <%= f.number_field :location %>
  </div> -->
  <div class="field">
  <i class="fa fa-calendar" aria-hidden="true"></i>
    <%= f.label 'Date of the Story' %><br>
    <%= f.date_select :date,start_year:2000 %>
  </div>

 

  <!-- <div class="field">
  <i class="fa fa-picture-o" aria-hidden="true"></i>
    <%= f.label :photos %><br>
    <%= f.text_field :photos %>
  </div><br>  -->



<div class="boxed">

<br><label><i class="fa fa-location-arrow" aria-hidden="true"></i>
( Transportation )</label><br><br>



  <label class="checkbox-inline">
  <div class="field">
  <i class="fa fa-bus" aria-hidden="true"></i>
    <%= f.label :bus %><br>
    <%= f.check_box :bus %>
  </div>
</label>


  <label class="checkbox-inline">
  <div class="field">
  <i class="fa fa-car" aria-hidden="true"></i>
    <%= f.label :car %><br>
    <%= f.check_box :car %>
  </div>
</label>


  <label class="checkbox-inline">
  <div class="field">
  <i class="fa fa-life-ring" aria-hidden="true"></i>
    <%= f.label :boat %><br>
    <%= f.check_box :boat %>
  </div>
</label>


  <label class="checkbox-inline">
  <div class="field">
  <i class="fa fa-plane" aria-hidden="true"></i>
    <%= f.label :plane %><br>
    <%= f.check_box :plane %>
  </div>
</label>

<%= f.file_field :image %>
  <label class="checkbox-inline">
  <div class="field">
<i class="fa fa-male" aria-hidden="true"></i>
    <%= f.label :walking %><br>
    <%= f.check_box :walking %>
  </div>
</label>


  <label class="checkbox-inline">
  <div class="field">
  <i class="fa fa-ticket" aria-hidden="true"></i>
    <%= f.label :train %><br>
    <%= f.check_box :train %>
  </div>
</label><br><br><br>
</div><br>

 <div class="field">
  <i class="fa fa-book" aria-hidden="true"></i>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>


  <label class="checkbox-inline">
  <div class="field">
  <i class="fa fa-lock" aria-hidden="true"></i>
    <%= f.label :privacy %>
    <%= f.check_box :privacy %>
  </div>
</label><br><br>

  <div class="actions">
    
    

<%= button_tag( :class => "btn btn-success") do %>
  Save Story <i class="fa fa-floppy-o" aria-hidden="true"></i>
<% end %>


  </div>
<% end %>

</div>

app/views/posts/edit.html.erb
<div class="maincontant text-center newpost">
<h1>Editing Story</h1>

<%= render 'form' %><br>

<%= link_to 'Show', @post,:class=>"btn btn-success" %> |
<%= link_to 'Back', posts_path,:class=>"btn btn-default" %>
</div>

app/views/posts/index.html.erb
<div class="maincontant text-center allposts">
<link href="https://fonts.googleapis.com/css?family=Baloo+Tamma" rel="stylesheet">
<link href="/posts.scss" rel="stylesheet">
<p id="notice"><%= notice %></p>

<div class="container-fluid">
<h1>All Stories</h1>

<%= image_tag("allstoriesimg.jpg", :class => "img img-responsive") %>
</div>
<div class="container">
  
   <% @posts.each do |post| %>
  <div class="col-md-4">

    <h4><%= post.title %></h4>

    <p class="datestyle"><%= post.date.strftime("%d %b %Y")  %></p>
    
    <% if post.privacy %>
      <i class="fa fa-lock" aria-hidden="true"></i>
    <% end %>
    <% if post.bus %>
      <i class="fa fa-bus" aria-hidden="true"></i>
    <% end %>
    <% if post.car %>
      <i class="fa fa-car" aria-hidden="true"></i>
    <% end %>
    <% if post.boat %>
      <i class="fa fa-life-ring" aria-hidden="true"></i>
    <% end %>
    <% if post.plane %>
      <i class="fa fa-plane" aria-hidden="true"></i>
    <% end %>
    <% if post.walking %>
      <i class="fa fa-male" aria-hidden="true"></i>
    <% end %>
    <% if post.train %>
      <i class="fa fa-ticket" aria-hidden="true"></i>
    <% end %>

    <p class="text-muted"><%= post.text.truncate(100) %><%= link_to '(more)', post%></p>
    <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
    
    <hr class="primary">   
</div>  
<% end %>

</div>


<br>



</div>

app/views/posts/myposts.html.erb
<div class="maincontant text-center"><br>

<link href="/posts.scss" rel="stylesheet">
<p id="notice"><%= notice %></p>

<h1>My Stories</h1><br>
<%= image_tag("books.jpg", :class => "img img-responsive") %><br>
<div class="container">
   <% @myposts.each do |post| %>
  <div class="col-sm-3">
    <h4><%= post.title %></h4>

    <p class="datestyle"><%= post.date.strftime("%d %b %Y")  %></p>
    
    <% if post.privacy %>
      <i class="fa fa-lock" aria-hidden="true"></i>
    <% end %>
    <% if post.bus %>
      <i class="fa fa-bus" aria-hidden="true"></i>
    <% end %>
    <% if post.car %>
      <i class="fa fa-car" aria-hidden="true"></i>
    <% end %>
    <% if post.boat %>
      <i class="fa fa-life-ring" aria-hidden="true"></i>
    <% end %>
    <% if post.plane %>
      <i class="fa fa-plane" aria-hidden="true"></i>
    <% end %>
    <% if post.walking %>
      <i class="fa fa-male" aria-hidden="true"></i>
    <% end %>
    <% if post.train %>
      <i class="fa fa-ticket" aria-hidden="true"></i>
    <% end %>

    <p class="text-muted"><%= post.text.truncate(100) %><%= link_to '(more)', post%></p>
    
    <hr class="primary">
    <%= link_to 'Edit', edit_post_path(post),:class=>"btn btn-warning"   %>
    
  </div>
  <% end %>
</div>


<br>



</div>

app/views/posts/new.html.erb
<div class="maincontant text-center newpost"><br>
<link href="/posts.scss" rel="stylesheet">

<h1>New Story</h1><br>

<%= render 'form' %><br>

<%= link_to 'Back', posts_path,:class=>"btn btn-default" %>

</div>

app/views/posts/show.html.erb
<div class="maincontant text-center showpost">

<link href="/posts.scss" rel="stylesheet">
<p id="notice"><%= notice %></p><br>

<h1>
  <%= @post.title %>
</h1>

<!-- <p>
  <strong>Location:</strong>
  <%= @post.location %>
</p> -->


  <p class="datestyle"><%= @post.date.strftime("%d %b %Y")  %></p>




<!-- <p>
  <strong>Photos:</strong>
  <%= @post.photos %>
</p> -->


    <% if @post.privacy %>
      <i class="fa fa-lock" aria-hidden="true"></i>
    <% end %>
    <% if @post.bus %>
      <i class="fa fa-bus" aria-hidden="true"></i>
    <% end %>
    <% if @post.car %>
      <i class="fa fa-car" aria-hidden="true"></i>
    <% end %>
    <% if @post.boat %>
      <i class="fa fa-life-ring" aria-hidden="true"></i>
    <% end %>
    <% if @post.plane %>
      <i class="fa fa-plane" aria-hidden="true"></i>
    <% end %>
    <% if @post.walking %>
      <i class="fa fa-male" aria-hidden="true"></i>
    <% end %>
    <% if @post.train %>
      <i class="fa fa-ticket" aria-hidden="true"></i>    
    <% end %><br><br>

<div class="container">

      <!-- Main component for a primary marketing message or call to action -->
      <div class="col-md-9 col-md-offset-1">
<p class="text-muted">
  <%= @post.text %>
</p><br><br><br>
</div class="col-md-12">

  <%= image_tag @post.image_url(:thumb).to_s, class:"thumbnail" %>
</div>
<br><br><br><br>



<%= link_to 'Back', posts_path,:class=>"btn btn-default" %>
</div>

app/views/profils/edit.html.erb
<div class="maincontant"><br>



<%= render 'form' %>


</div>
<div class="text-center">
<%= link_to 'Show', @profil %>
</div>

app/views/profils/index.html.erb
<div class="maincontant">

<p id="notice"><%= notice %></p>

<div class="container">


<h1>Listing Profils</h1>



<table class="table">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Bio</th>
      <th>City of origin</th>
      <th>Current location</th>
      <th>Asylum status</th>
      <th>Email</th>
      <th>Facebook</th>
      <th>Twitter</th>
      <th>Linkedin</th>
      <th>Instagram</th>
      <th>Dob</th>
      <th>Gender</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profils.each do |profil| %>
      <tr>
        <td><%= profil.first_name %></td>
        <td><%= profil.last_name %></td>
        <td><%= profil.bio %></td>
        <td><%= profil.city_of_origin %></td>
        <td><%= profil.current_location %></td>
        <td><%= profil.asylum_status %></td>
        <td><%= profil.email %></td>
        <td><%= profil.facebook %></td>
        <td><%= profil.twitter %></td>
        <td><%= profil.linkedin %></td>
        <td><%= profil.instagram %></td>
        <td><%= profil.dob %></td>
        <td><%= profil.gender %></td>
        <td><%= link_to 'Show', profil %></td>
        <td><%= link_to 'Edit', edit_profil_path(profil) %></td>
        <td><%= link_to 'Destroy', profil, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profil', new_profil_path %>

</div>
</div>

app/views/profils/show.html.erb
<div class="maincontant">

  <p id="notice"><%= notice %></p>
  <div class="container">
    <div class="row profile">
      <div class="col-md-3">
        <div class="profile-sidebar solid">
          <!-- SIDEBAR USERPIC -->
          <div class="profile-userpic">

            <%= image_tag @profil.image_url(:thumb).to_s, class:"thumbnail" %>

          </div>
          <!-- END SIDEBAR USERPIC -->
          <!-- SIDEBAR USER TITLE -->
          <div class="profile-usertitle">
            <div class="profile-usertitle-name">


              <%= @profil.first_name %>
              <%= @profil.last_name %><br>
              
              <strong>Gender:</strong>
              <%= @profil.gender %>
            </div>
            <div class="profile-usertitle-job">
              <strong>City of Origin:</strong>
              <%= @profil.city_of_origin %><br>
              <strong>Current Location:</strong>
              <%= @profil.current_location %><br>
              <strong>Date of Birth:</strong>
              <%= @profil.dob.strftime("%d %b %Y")%><br>
              <strong>Asylum Status:</strong>
              <%= @profil.asylum_status %>
              

            </div>
          </div>
          <!-- END SIDEBAR USER TITLE -->
          <!-- SIDEBAR BUTTONS -->
          <div class="profile-userbuttons">
            <button type="button" class="btn btn-success btn-sm"><%= link_to 'Edit My Profile', edit_profil_path(@profil), :class =>"editmypro" %></button>
            <a href="mailto:<%= @profil.email %>"><button type="button" class="btn btn-danger btn-sm"><i class="fa fa-envelope-o" aria-hidden="true"></i>
             Message</button></a>

           </div>
           <!-- END SIDEBAR BUTTONS -->
           <!-- SIDEBAR MENU -->
           <div class="profile-usermenu">
            <ul class="nav">
              <li class="active">
                

                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  <i class="glyphicon glyphicon-home"></i>
                  Overview </a>

                </li>
                <li>
                  
                  <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    <i class="fa fa-book" aria-hidden="true"></i> My Stories
                  </a>                                          
                </li>

                <li>
                  <a href="/users/edit">
                    <i class="glyphicon glyphicon-user"></i>
                    Account Settings </a>
                  </li>
                  



                  <li>
                    <a href="#">
                      <i class="glyphicon glyphicon-flag"></i>
                      Help </a>
                    </li>
                  </ul>
                </div>
                <!-- END MENU -->
              </div>
            </div>
            <div class="col-md-9">
              <div class="profile-content solid">
              <div id="accordion" role="tablist" aria-multiselectable="true">
              
             
              <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
      </h4>
    </div>
    

    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                  <strong>Bio:</strong>
                  <%= @profil.bio %>

                 <div class="socialmediaicons">
                <% unless @profil.facebook.blank? %> 

                <a href="<%= @profil.facebook %>" target="_blank"><i class="fbcolor fa fa-4x fa-facebook-square" aria-hidden="true"></i>
                </a><br>
                <% end %>

                <% unless @profil.twitter.blank? %>
                <a href="<%= @profil.twitter %>" target="_blank"><i class="twcolor fa fa-4x fa-twitter-square" aria-hidden="true"></i>
                </a><br>
                <% end %>

                <% unless @profil.linkedin.blank? %>
                <a href="<%= @profil.linkedin %>" target="_blank"><i class="fa fa-4x fa-linkedin-square" aria-hidden="true"></i>
                </a><br>
                <% end %>

                <% unless @profil.instagram.blank? %>
                <a href="http://www.instagram.com/<%= @profil.instagram %>" target="_blank"><i class="incolor fa fa-4x fa-instagram" aria-hidden="true"></i></a>
                <% end %>
              </div>

                </div>
                </div>

                
                <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                  <div class="row">
                   <% @myposts.each do |post| %>
                   <div class="col-sm-3 text-center">


                     <h4><%= post.title %></h4>

                     <p class="datestyle"><%= post.date.strftime("%d %b %Y")  %></p>

                     <% if post.privacy %>
                     <i class="fa fa-lock" aria-hidden="true"></i>
                     <% end %>
                     <% if post.bus %>
                     <i class="fa fa-bus" aria-hidden="true"></i>
                     <% end %>
                     <% if post.car %>
                     <i class="fa fa-car" aria-hidden="true"></i>
                     <% end %>
                     <% if post.boat %>
                     <i class="fa fa-life-ring" aria-hidden="true"></i>
                     <% end %>
                     <% if post.plane %>
                     <i class="fa fa-plane" aria-hidden="true"></i>
                     <% end %>
                     <% if post.walking %>
                     <i class="fa fa-male" aria-hidden="true"></i>
                     <% end %>
                     <% if post.train %>
                     <i class="fa fa-ticket" aria-hidden="true"></i>
                     <% end %>

                     <p class="text-muted"><%= post.text.truncate(50) %><%= link_to '(more)', post%></p>

                     <hr class="primary">
                     <%= link_to 'Edit', edit_post_path(post),:class=>"btn btn-warning"   %>


                   </div>
                   <% end %>
                 </div>
               </div>
              </div>
              </div>


              







            </div>
          </div>
        </div>
      </div>
      <center>







      </div>

app/views/profils/showtest.html.erb
<div class="maincontant">

  <p id="notice"><%= notice %></p>
  <div class="container">
    <div class="row profile">
      <div class="col-md-3">
        <div class="profile-sidebar solid">
          <!-- SIDEBAR USERPIC -->
          <div class="profile-userpic">

            <%= image_tag @profil.image_url(:thumb).to_s, class:"thumbnail" %>

          </div>
          <!-- END SIDEBAR USERPIC -->
          <!-- SIDEBAR USER TITLE -->
          <div class="profile-usertitle">
            <div class="profile-usertitle-name">


              <%= @profil.first_name %>
              <%= @profil.last_name %><br>
              
              <strong>Gender:</strong>
              <%= @profil.gender %>
            </div>
            <div class="profile-usertitle-job">
              <strong>City of Origin:</strong>
              <%= @profil.city_of_origin %><br>
              <strong>Current Location:</strong>
              <%= @profil.current_location %><br>
              <strong>Date of Birth:</strong>
              <%= @profil.dob.strftime("%d %b %Y")%><br>
              <strong>Asylum Status:</strong>
              <%= @profil.asylum_status %>
              

            </div>
          </div>
          <!-- END SIDEBAR USER TITLE -->
          <!-- SIDEBAR BUTTONS -->
          <div class="profile-userbuttons">
            <button type="button" class="btn btn-success btn-sm"><%= link_to 'Edit My Profile', edit_profil_path(@profil), :class =>"editmypro" %></button>
            <a href="mailto:<%= @profil.email %>"><button type="button" class="btn btn-danger btn-sm"><i class="fa fa-envelope-o" aria-hidden="true"></i>
             Message</button></a>

        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Collapsible Group Item #1
        </a>
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Collapsible Group Item #2
        </a>
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Collapsible Group Item #3
        </a>
           </div>
           <!-- END SIDEBAR BUTTONS -->
           <!-- SIDEBAR MENU -->
           <div class="profile-usermenu">
            
            </div>
            <!-- END MENU -->
          </div>
          </div>
  
<div class="col-md-9">
              <div class="profile-content solid">







  <div id="accordion" role="tablist" aria-multiselectable="true">
  
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
      </h4>
    </div>
    

    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
    </div>
  </div>
  

</div>
</div>



            </div>
          </div>
        </div>
      </div>
      <center>







      </div>